# ======================== #
name: Python Application
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
# ======================== #
jobs:
  Builds:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.10", "3.10", "3.10", "3.10", "3.10", "3.10", "3.10", "3.10", "3.10"]
    timeout-minutes: 10
# ======================== #
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install stem pydub SpeechRecognition selenium requests undetected-chromedriver==1.5.2
    - name: Install Chrome & Update
      run: |
        sudo apt-get update && sudo apt-get install psmisc wget git curl ffmpeg -y
        sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo apt-get install ./google-chrome-stable_current_amd64.deb -y
    - name: Start
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        git clone https://Musik21:$TOKEN@github.com/Musik21/Private.git && cd Private && python3 linux.py
# ======================== #
